version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fakestack
  fakestack:
    image: fakestack
    depends_on:
      - postgres
    environment:
      FAKESTACK_DB_USERNAME: postgres
      FAKESTACK_DB_PASSWORD: password
      FAKESTACK_DB_PORT: 5432
      FAKESTACK_DB_HOST: postgres
      FAKESTACK_DB_DBNAME: fakestack
      FAKESTACK_DB_SSL_MODE: disable
      FAKESTACK_SERVER_PORT: 8080
    restart: unless-stopped
    expose:
      - 8080
  proxy:
    image: nginx
    depends_on: 
      - fakestack
    ports: 
      - "8080:8080"
    volumes:
      - type: bind
        source: ./tmp/nginx.conf
        target: /etc/nginx/nginx.conf
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus.yml
    depends_on: 
      - fakestack
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
